db:
  production:
    adapter:  postgresql
    host:     localhost
    encoding: utf8
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    database: <%= ENV['DATABASE_NAME']%>
    pool: 5
    timeout: 5000

  development:
    adapter:  postgresql
    host:     localhost
    encoding: utf8
    username: <%= ENV['DEV_DATABASE_USERNAME'] %>
    password: <%= ENV['DEV_DATABASE_PASSWORD'] %>
    database: <%= ENV['DEV_DATABASE_NAME']%>
    pool: 5
    timeout: 5000
