db:
  production:
    adapter:  mysql2
    socket: /tmp/mysql.sock
    host:     localhost
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    database: <%= ENV['DATABASE_NAME']%>

  development:
    adapter:  mysql2
    socket: /tmp/mysql.sock
    host:     localhost
    username: <%= ENV['DEV_DATABASE_USERNAME'] %>
    password: <%= ENV['DEV_DATABASE_PASSWORD'] %>
    database: <%= ENV['DEV_DATABASE_NAME']%>
